language: php
dist:     bionic
php:
 - '7.2'

# Only build main branches : feature branches will be covered by the PR builder
branches:
  only:
    - /^[0-9\.]+\.x$/

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
 - composer self-update
 - composer install --no-interaction

script:
 - vendor/bin/phpunit
